# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReceiveData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ReceiveData.proto\x1a\x1egoogle/protobuf/wrappers.proto\"4\n\x11SampleRequestList\x12\x1f\n\x07reqList\x18\x01 \x03(\x0b\x32\x0e.SampleRequest\"1\n\rSampleRequest\x12\x12\n\nlabelValue\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2Q\n\x0cLabelService\x12\x41\n\rreceiveSample\x12\x12.SampleRequestList\x1a\x1a.google.protobuf.BoolValue\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReceiveData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLEREQUESTLIST._serialized_start=53
  _SAMPLEREQUESTLIST._serialized_end=105
  _SAMPLEREQUEST._serialized_start=107
  _SAMPLEREQUEST._serialized_end=156
  _LABELSERVICE._serialized_start=158
  _LABELSERVICE._serialized_end=239
# @@protoc_insertion_point(module_scope)
